server:
  servlet:
    context-path: /demo
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xkcoding-security?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SecurityDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update